---

- hosts: localhost
  roles:
    - ansible-output-prettify

- hosts: localhost
  connection: local
  become: true
  tasks:

    - name: 'Install AUR wrapper'
      when: ansible_os_family == "Archlinux"
      ansible.builtin.package:
        name: yay
        state: present

    - name: 'Install AUR dependencies'
      when: ansible_os_family == "Archlinux"
      community.general.pacman:
        name:
          - trash-cli
          - gtk-engine-murrine
          - visual-studio-code-bin
          - gruvbox-plus-icon-theme
        state: present
        executable: yay
